### PR TITLE
Add `spanish` translation and minor fixes

### PR DESCRIPTION
**Pull request by juliolopeztorres**
Hi there!

First of all, thank you for sharing this amazing project and code to all of us, including `nitrogen`  repo.

I would like to contribute back a bit to your project by adding a simple `spanish` translation, as it is my mother tongue.

Besides that, I was playing around with your code and found that `/not-found` route was being handled by `express` instead of `react` through the sample `static site ui`. For that reason, I debugged a bit and found that `/not-found` route was missing inside the `backend` or `service`  code.

I updated that piece of code and translated the hardcoded message on `/not-found` component. 

Please, consider the translations I have added (new key `message.page-not-found`) under `ta` and `fr` languages as examples. I translated from english to those languages using Google Translate.

Hope you find this useful.

## Summary by CodeRabbit

- **New Features**
	- Added a new route for handling "Page Not Found" scenarios.
	- Introduced localization for user authentication system in Spanish and updates in other languages.

- **Bug Fixes**
	- Corrected typo in error message keys across multiple language files.
	- Enhanced error message handling in the `Login` and `GetCode` components.

- **Documentation**
	- Updated error and informational messages in English, French, and Tamil to improve clarity and consistency.

### CODE REVIEW

**Comment by shrihari-prakash** [comment]
Hello @juliolopeztorres , 
Thanks a lot for your interest in the project and the translations! Really appreciate it! 💯💯

About the 404, it is true that the response from API is not looking so elegant. I previously considered adding a 404 page, however, the problem is that express would still return 200 and we would know it is a 404 only after it actually rendered the `index.html`. This might most times confuse developers.
For instance, I do a POST from my application to a mistyped API route from my custom app. The request would result in a HTML page with 200 status code potentially misleading the developer that the API worked if they did not inspect the response.

Do you see any way to return a 404 in the index?

**Comment by juliolopeztorres** [comment]
Hey there!

I totally see your point. From that point of view, I can understand why the code looked like that. 

Well, all I can say is putting everything related to the `backend` (or `oauth`) behind a certain URL path. I would say that everything that answers in `JSON` format (as representing end-to-end machine conversations), should be under `/api` path (or similar). 

That way, you could handle two different "systems" as its corresponding errors, one human-oriented (200 domain.com/fake-path answering HTML) and the other system for developers or machines answering in `JSON` format (404 domain.com/api/my-fake-path)

What do you think about this possibility?

**Comment by shrihari-prakash** [comment]
Hello @juliolopeztorres ,
I think ideally this should be the case. However, it is important to assess the breaking changes associated with this. I created issue #33 to deep dive into this. Let us merge the translations and try to find a tradeoff about the 404.

**Comment by shrihari-prakash** [comment]
Could you edit the Tamil translation in the PR?

**Comment by shrihari-prakash** [comment]
@juliolopeztorres , I also realized perhaps we can handle the 404s in a hybrid mode. There is only 3 categories of APIs, OAuth, User and System. This means, for all routes starting with a `/user`, `/oauth` and `/system`, a JSON based 404 can be provided and for all others, the static page can be provided. 

I prefer this over having a `/api` prefix because for the OAuth module, routes like `/api/oauth` would look non standard although they look cleaner on `/api/user` and `/api/system`.

I will implement this in a separate PR.

**Review by shrihari-prakash — APPROVED** [review]

**Comment by juliolopeztorres** [comment]
Sorry for the delay in responding you. 

Thanks for taking the time to consider this PR and also always thank you for sharing your code.

**Pull request merged**
